In [1]:
# Creating a Dictionary of Data
import pandas as pd
data_Lists = {"Name":["Avery", "Amanda","Collins","Sandra","Mark", "Kingsley","Whitney","Isabella","Cyril","Ben"],
             "Countries":["England", "Spain","Brasil","Portugal","Greece","Sweden","France","Italy","Russia","Japan"], 
              "Age":[34,56,76,45,36,48,42,29,31,50],
               "Scores":[45.87, 56.89,105.67,87.34,35.20,59.12,95.13,50.02, 64.32,70.67]}

In [2]:
#Creating a DataFrame from the Dictionary
Originallists = pd.DataFrame(data_Lists)
print(Originallists)

       Name Countries  Age  Scores
0     Avery   England   34   45.87
1    Amanda     Spain   56   56.89
2   Collins    Brasil   76  105.67
3    Sandra  Portugal   45   87.34
4      Mark    Greece   36   35.20
5  Kingsley    Sweden   48   59.12
6   Whitney    France   42   95.13
7  Isabella     Italy   29   50.02
8     Cyril    Russia   31   64.32
9       Ben     Japan   50   70.67


In [3]:
Originallists.Countries

0     England
1       Spain
2      Brasil
3    Portugal
4      Greece
5      Sweden
6      France
7       Italy
8      Russia
9       Japan
Name: Countries, dtype: object

In [4]:
Originallists.Scores

0     45.87
1     56.89
2    105.67
3     87.34
4     35.20
5     59.12
6     95.13
7     50.02
8     64.32
9     70.67
Name: Scores, dtype: float64

In [5]:
Originallists.Name

0       Avery
1      Amanda
2     Collins
3      Sandra
4        Mark
5    Kingsley
6     Whitney
7    Isabella
8       Cyril
9         Ben
Name: Name, dtype: object

In [6]:
# get the first five rows

Originallists = pd.DataFrame(data_Lists)
Originallists1 = Originallists.head(5)
print(Originallists1)

      Name Countries  Age  Scores
0    Avery   England   34   45.87
1   Amanda     Spain   56   56.89
2  Collins    Brasil   76  105.67
3   Sandra  Portugal   45   87.34
4     Mark    Greece   36   35.20


In [7]:
Originallists.columns 

Index(['Name', 'Countries', 'Age', 'Scores'], dtype='object')

In [8]:
 
# rename of columns using the lists method of naming all the columns
Originallists.columns = ["First Name","Countries","Age","Scores"]
Originallists.head(5)

First Name Countries  Age  Scores
0      Avery   England   34   45.87
1     Amanda     Spain   56   56.89
2    Collins    Brasil   76  105.67
3     Sandra  Portugal   45   87.34
4       Mark    Greece   36   35.20

In [9]:
# rename columns using the second method  rename()function
data_Lists =  Originallists.rename(columns = ({"Countries":"Locations"}),inplace = True, )
Originallists.head(5)

First Name Locations  Age  Scores
0      Avery   England   34   45.87
1     Amanda     Spain   56   56.89
2    Collins    Brasil   76  105.67
3     Sandra  Portugal   45   87.34
4       Mark    Greece   36   35.20

In [10]:
# using pandas.DataFrame.astype() to change the data type of a specfic column

Originallists = Originallists.astype({"Age":float}) # integers to floats
print(Originallists)

  First Name Locations   Age  Scores
0      Avery   England  34.0   45.87
1     Amanda     Spain  56.0   56.89
2    Collins    Brasil  76.0  105.67
3     Sandra  Portugal  45.0   87.34
4       Mark    Greece  36.0   35.20
5   Kingsley    Sweden  48.0   59.12
6    Whitney    France  42.0   95.13
7   Isabella     Italy  29.0   50.02
8      Cyril    Russia  31.0   64.32
9        Ben     Japan  50.0   70.67


In [11]:
Originallists.loc[2,"Locations"]

'Brasil'

In [12]:
Originallists.iloc[2,1]

'Brasil'

In [13]:
# renaming the index rows
Originallists.index = ("One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten")
print(Originallists)

      First Name Locations   Age  Scores
One        Avery   England  34.0   45.87
Two       Amanda     Spain  56.0   56.89
Three    Collins    Brasil  76.0  105.67
Four      Sandra  Portugal  45.0   87.34
Five        Mark    Greece  36.0   35.20
Six     Kingsley    Sweden  48.0   59.12
Seven    Whitney    France  42.0   95.13
Eight   Isabella     Italy  29.0   50.02
Nine       Cyril    Russia  31.0   64.32
Ten          Ben     Japan  50.0   70.67


In [14]:
Originallists.set_index("First Name",inplace = True)
print(Originallists)

           Locations   Age  Scores
First Name                        
Avery        England  34.0   45.87
Amanda         Spain  56.0   56.89
Collins       Brasil  76.0  105.67
Sandra      Portugal  45.0   87.34
Mark          Greece  36.0   35.20
Kingsley      Sweden  48.0   59.12
Whitney       France  42.0   95.13
Isabella       Italy  29.0   50.02
Cyril         Russia  31.0   64.32
Ben            Japan  50.0   70.67


In [15]:
# Reset the index
Originallists.reset_index()

First Name Locations   Age  Scores
0      Avery   England  34.0   45.87
1     Amanda     Spain  56.0   56.89
2    Collins    Brasil  76.0  105.67
3     Sandra  Portugal  45.0   87.34
4       Mark    Greece  36.0   35.20
5   Kingsley    Sweden  48.0   59.12
6    Whitney    France  42.0   95.13
7   Isabella     Italy  29.0   50.02
8      Cyril    Russia  31.0   64.32
9        Ben     Japan  50.0   70.67

In [16]:
# creating a 2D array
import numpy as np
array = np.array([[11, 12, 2], [ 8,15,10], [12,15,6],[4,16,9]])


In [17]:
print(array)

[[11 12  2]
 [ 8 15 10]
 [12 15  6]
 [ 4 16  9]]


In [18]:
array.shape

(4, 3)

In [19]:
#Transpose array
array = np.array([[11, 12, 2], [ 8,15,10], [12,15,6],[4,16,9]])
array1 = array.transpose()
print(array1)

[[11  8 12  4]
 [12 15 15 16]
 [ 2 10  6  9]]


In [21]:
#print shape
array1.shape

(3, 4)

In [22]:
#create a random array as array2 with the column having the same column  size as  the row size in the first 2D array
import numpy as np
array2 = np.random.randint(5, size = (3,4))
print("Random set of rows from 2D array array:")
print(array2)


Random set of rows from 2D array array:
[[4 0 4 0]
 [0 4 4 3]
 [2 2 3 2]]


In [23]:
#multipy the transpose array by the new random array created using the * operator
array3 = array1*array2 
print(array3)

[[44  0 48  0]
 [ 0 60 60 48]
 [ 4 20 18 18]]


In [24]:
#multipy the transpose array by the new random array created using the multiply()function
array3 = np.multiply(array1,array2)
print(array3)

[[44  0 48  0]
 [ 0 60 60 48]
 [ 4 20 18 18]]
